### ISSUE TITLE
<USER STORY> Social media links

### ISSUE THREAD

**Issue by Libbu** [Libbu/travel-site-practice-for-hackaton#3]
As a user I want to see travel website social media links so that I can follow them for content on other channels
### Acceptance Criteria

- Acceptance Criteria 1: travel destination company has social media presence.
- Acceptance Criteria 2: links to social media display consistently on all pages in site 
- Acceptance Criteria 3: links to social media take user to travel company social media page

### Tasks

- [ ] get Travel destination company social medai URLs
- [ ] develop code for social media links in footer
- [ ] link to relevant social media
