### ISSUE TITLE
<USER STORY> Pictures on website

### ISSUE THREAD

**Issue by Libbu** [Libbu/travel-site-practice-for-hackaton#5]
As a user I want to see high quality pictures of the destinations so that I can decide where to go. 

### Acceptance Criteria

- Acceptance Criteria 1: pictures of destinations appear on site
- Acceptance Criteria 2: picutes are relevant to the destination
- Acceptance Criteria 3: pictures are high quality

### Tasks

- [ ]  Source high quality pictures of destinations 
- [ ] optimise for web
- [ ] add image assets to website code
- [ ] style image assetst on website
