### ISSUE TITLE
<USER STORY> Site Owner porpose of site

### ISSUE THREAD

**Issue by Libbu** [Libbu/travel-site-practice-for-hackaton#6]
As a website owner I want to provide organised content on a variety of destinations to showcase them to users

### Acceptance Criteria

- Acceptance Criteria 1: Site exists
- Acceptance Criteria 2: Site contains different categories of travel destination
- Acceptance Criteria 3: Site can be clearly navigated

### Tasks

- [ ] Develop code for website
- [ ] Develop different pages for different destination types
- [ ] develop nav bar
