### ISSUE TITLE
<USER STORY> Site Owner social media links

### ISSUE THREAD

**Issue by Libbu** [Libbu/travel-site-practice-for-hackaton#8]
As a site owner I want links to my social media displayed consistently across my website pages so that I can grow my following on those social media websites.

### Acceptance Criteria

- Acceptance Criteria 1: Travel business has a social media presence
- Acceptance Criteria 2: Social media links are visible on all pages of website
- Acceptance Criteria 3: Social media links connect to relevant social media pages

### Tasks

- [ ] develop social media section in header or footer for webpage
- [ ] insert social media platform icons
- [ ] link social media icons to relevant social media pages
