### ISSUE TITLE
<USER STORY> Site owner text content

### ISSUE THREAD

**Issue by Libbu** [Libbu/travel-site-practice-for-hackaton#9]
As a site owner I want to provide detailed, comprehensive information on travel destinations to help inform people about what they are and what to expect

### Acceptance Criteria

- Acceptance Criteria 1: Travel webstie structure clearly allows users to find information on different destinations
- Acceptance Criteria 2: detailed text information appears with images in the website so it is clear they are linked
- Acceptance Criteria 3: text information is clearly presented and readable

### Tasks

- [ ] develop page structure of travel website
- [ ] place relevant text information in corresponding destination section
- [ ] style with fonts, font-sizes and background contrast to promote readability
